@url=http://localhost:8080/post

# CREATE NEW LETTER IMAGE
POST  {{url}}/postImages HTTP/1.1
Content-Type: application/json
Authorization:hasan@gmail.com

{
  "files":"Hello"
}


###
# CREATE NEW LETTER POST
POST {{url}}/Text HTTP/1.1
Content-Type: application/json

{
  "letter":"Hello World",
  "email":"hasan@gmail.com"
}
###
# GET POSTS by USER ID
GET {{url}}s/hasan@gmail.com HTTP/1.1
###
GET http://localhost:8080/posts HTTP/1.1
Authorization: hasan@gmail.com
###
# LIKE
POST http://localhost:8080/post/likee/11
Content-Type: application/json

{
  "email":"hasan@gmail.com"
}


### 
# DISLIKE
POST http://localhost:8080/post/dislikee/1
Content-Type: application/json

{
  "email":"hasan@gmail.com"
}

###
DELETE http://localhost:8080/post/25
Content-Type: application/json
Authorization: hasan@gmail.com

{
  "email":"hasan@gmail.com"
}

###
POST http://localhost:8080/post/checkSaved/2
Content-Type: application/json

{
  "email":"hasan@gmail.com"
}