GET http://localhost:8080 HTTP/1.1

###
DELETE http://localhost:8080/7

###
POST http://localhost:8080/register
Content-Type: application/json

{
    "name":"Xasanboy",
    "lastname":"Abdurasulov",
    "email":"hasanbojabdurasulov@gmail.com",
    "password":"1234"
}
###
POST http://localhost:8080/login
Content-Type: multipart/form-data

{
    "email":"hasanbojabdurasulov@gmail.com",
    "password":"1234"
}

###
GET http://localhost:8080/users HTTP/1.1
Content-Type:application/json

{
    "name":"Xasanboy"
}
###
GET http://localhost:8080 HTTP/1.1

###
GET http://localhost:8080/posts/hasan@gmail.com